Riribranch
Riael42/PPSD_FT_LS pull request #11
Opened 2023-03-06 17:00 UTC by Riael42

Please check this carefully before merging and decline it if you want any changes

2023-03-11 13:48 UTC, mc-putchar requested changes
While this might be outdated, still wanted to check your approach and see if we can raise some extra questions relevant for future work. And also practice reviewing as it's my first time =)

2023-03-11 13:48 UTC, mc-putchar commented on srcs/ft_proc_args.c
> +	char	flags[53]; //hard cap at 26 * 2 flags
no need to hard cap flags that low (or at all)

2023-03-11 13:48 UTC, mc-putchar commented on srcs/ft_proc_args.c
>  	bitshift = ft_get_bitshift(flags);
`int	ft_get_bits(int ac, char **av);`
This is the new prototype to get the bits from.

2023-03-11 13:48 UTC, mc-putchar commented on srcs/ft_flag_arg.c
> +	while (argv[argc][argpar] != '\0')
if `argv[argc] == ""`, this will be out of bounds and cause Segmentation fault

2023-03-11 13:48 UTC, mc-putchar commented on srcs/ft_flag_arg.c
> +#include "../includes/ft_ls.h"
perhaps just `#include "ft_ls.h" `
and in makefile we can point the compiler to where header files are

2023-03-11 13:48 UTC, mc-putchar commented on srcs/ft_proc_args.c
> -		write(1, "Invalid name error, replace this with specific flag error", 20);
Maybe error handling warrants calling separate function just for that?
Also, don't forget to write error messages to `stderror(2)`, not `stdout(1)`

2023-03-12 10:19 UTC, Riael42 commented on srcs/ft_flag_arg.c
> +#include "../includes/ft_ls.h"
True

2023-03-12 10:21 UTC, Riael42 commented on srcs/ft_flag_arg.c
> +#include "../includes/ft_ls.h"
Let's perhaps get a crude makefile going and just carry that around in the repo for quick compiling and testing

2023-03-12 10:26 UTC, Riael42 commented on srcs/ft_proc_args.c
> +	char	flags[53]; //hard cap at 26 * 2 flags
Let's have an optional function somewhere that increases it if needed, I'd rather we continue to avoid useless calls where we can.

Perhaps we should save the number of flags in the config and if it's bigger than 53 we malloc extras?

2023-03-12 10:28 UTC, closed without merging

2023-03-12 10:28 UTC, Riael42 commented
Will fix and return

2023-03-12 10:38 UTC, Riael42 commented on srcs/ft_flag_arg.c
> +	while (argv[argc][argpar] != '\0')
Can't check right now but does it? 

Off the top of my head "" doesn't get inside the while because argv[x][0] == '\0';

Will check at home